import reader
import analyzer
content=reader.read_file()
line_count, word_count, blank_line_count, character_count, for_loops_count, while_loops_count, if_statements_count, functions_count , variables_count, variables, count_datatype, used_datatypes,count_return,return_list,Display_variables,variables_used,variables_unused= analyzer.analyze_content(content)
print("\n-----content of the file-----\n",content)
print("\n--------Analysis report--------\n",)
print("Total number of lines:   \n", line_count)
print("Total number of words:   \n", word_count)
print("Total number of blank lines:   \n", blank_line_count)
print("Total number of characters:   \n", character_count)
print("Total number of for loops:   \n", for_loops_count)
print("Total number of while loops:   \n", while_loops_count)
print("Total number of if statements:   \n", if_statements_count)
print("Total number of functions:    \n", functions_count)
print("Total number of variables:   \n", variables_count)
print("Variables: \n", variables)
print("Total number of datatypes:   \n",count_datatype)
print("Used datatypes:   \n",used_datatypes)
print("total number of return in the code:    \n",count_return)
print("list of return in the code    \n",return_list)
print("list of variables \n",Display_variables)
print("list of used variables \n",variables_used)
print("lisr of unused variables \n",variables_unused)

print("\n-------------------------------\n")

